# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  buildtest:
    image: buildtest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5265:5265
